"""Application constants."""

APP_NAME = "qry"
VERSION = "0.1.0"

DEFAULT_THEME = "dark"
DEFAULT_TAB_SIZE = 2
DEFAULT_PAGE_SIZE = 100
DEFAULT_MAX_COLUMN_WIDTH = 50
DEFAULT_HISTORY_SIZE = 1000
DEFAULT_TIMEOUT_MS = 30000

NULL_DISPLAY = "NULL"
